// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personajes.Data;

namespace Personajes.Data.Migrations
{
    [DbContext(typeof(PersonajesContext))]
    [Migration("20190822044012_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Personajes.Modelos.Atributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("destreza");

                    b.Property<int>("fuerza");

                    b.Property<string>("nombre");

                    b.Property<int>("puntosdegolpe");

                    b.Property<int>("vitalidad");

                    b.HasKey("Id");

                    b.ToTable("Atributos");
                });

            modelBuilder.Entity("Personajes.Modelos.Habilidad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AtributoId");

                    b.Property<string>("nombreHabilidad");

                    b.Property<int>("poder");

                    b.HasKey("id");

                    b.HasIndex("AtributoId");

                    b.ToTable("Habilidades");
                });

            modelBuilder.Entity("Personajes.Modelos.Habilidad", b =>
                {
                    b.HasOne("Personajes.Modelos.Atributo")
                        .WithMany("Habilidades")
                        .HasForeignKey("AtributoId");
                });
#pragma warning restore 612, 618
        }
    }
}
